### ISSUE TITLE
音乐素材

### ISSUE THREAD

**Issue by liguanghe** [13416136446/BP_Github#10]
我想到的是<红辣椒>op
 http://www.xiami.com/play?ids=/song/playlist/id/3320761/object_name/default/object_id/0#loaded

- 二/三/四部分:这首曲子的开头
- 一部分:这首曲子的中间部分

想到适合的曲子, 可以放进来哈~

**Comment by Irene6161** [comment]
背景音乐
[Red](http://music.163.com/#/song?id=28481787&autoplay=true&market=baiduhd)
Rob Simonsen

- 18秒到1分钟的时候，用来讲述

**Comment by liguanghe** [comment]
最终采用: http://www.xiami.com/song/2114139
