### ISSUE TITLE
路演准备, 伙伴们, 来发你的收获/感想和心得吧~

### ISSUE THREAD

**Issue by liguanghe** [13416136446/BP_Github#13]
## 找到隐喻,搞定产品
 
这个产品已经成熟成功,本身优点多, 

挑战在于, 如何能用三分钟,把它最精妙本质的点说出来, 让非程序员也能立即使用

找到它最核心的隐喻, 
自然界是树状结构生长的, 人的语言结构也是如此.
语言就是思想, 文字说不清楚的, 说话也一样说不清楚.
这些, 都好像我们把脑子连在树枝末梢的那一幕. 
当大树隐喻确立,这一切都说的很清楚了.

对于我们来说, 不过是还原了本体隐喻, 
而回到 github 创立之初,我们作为创始人, 
把 github 比作大树, 这是一个新的隐喻, 生出新的感觉, 也就有了伟大的产品. 

我们的题目是<树说> , 谐音"述说", 好记. 说,是沟通,协作中的沟通. 树说, 像树一样协作沟通, 用树来沟通协作.也可以说, 大树说, 这样沟通协作吧. 

**隐喻找对了, 产品和故事之间就非常稳固**, 

## 找到故事, 连接用户. 
找到隐喻只是作品有可能完成的第一步. 最初形成的key, 只是描述这种关系, 不能称为故事. 
想要故事性强, 对这个产品不断了解的过程之中, 不断的尝试用比喻来描述每个功能, 每个产品特性,等等, 这是在寻找故事的过程, 却很难串在一起. 绪龙给出的战争冲突, 也会考虑故事最本质要传达的特性是和谐, 那么战争因素就是不合适的. 

平和没有冲突. 新的成员随时加入, 用卡片大法和留意. 把上面描述的内容, 如大树,松鼠, 办公室的人, 分别写在卡片上, 发给组员六一, 

六一想到了功夫熊猫, 在现实中遭遇不满, 到森林里找高人指点, 满血复活回去改变世界. 好, 找到了第二个重要的角色, 引领者. 

英雄之旅的故事, 符合协作的积极主题.成功代入进来. 

当我灵感一现, 人和人在办公室摘下脑壳, 都不能把话说清楚的时候, 这个冲击让我知道故事成了. 

## 凤头 - 猪肚 - 豹尾
摘掉脑壳的这个开篇, 可以称得上凤尾.能够给人冲击/刺激, 也有冲突.

豹尾, 回归后的使用. 放眼全球的广阔意向, 以及带着树枝回到原来的地方,足够简短有力, 堪称豹尾.
这样的回归过程,利用大脑爱脑补, 读者完全可以代入自己, 想象之后的故事.带树枝回了, 也有隐喻橄榄枝回来的生机. 

凤头, 豹尾都有, 然后便是猪肚, 中间的这部分要详实, github 的功能那么多, 最核心的, 不可替代的是什么,选取哪些功能, 如何表达. 这里用图片推动故事. 因为有了人物, 和大树这样的背景做为道具, 我可以想象他们在这些背景下做了什么. 借鉴现有的 github 宣传片, 功能与功能之间变得流畅, 而不是独立的. 

功能太多, 需要取舍, 也有星星的内容, 这里会考虑突然出现的意向是不是突兀. 全篇出现的所有人物和背景, 都由绘画限制住, 多画一个人物, 就要增加读者的脑容量. 借助绘画, 在这个过程中, 也是要对产品的足够了解, 才可以明白. 

<balabala, 不讲废话> 这本书, 讲图文互相交错, 刺激灵感向前走, 就是这样. 永菲承担了几乎所有的绘图工作, 提供给团队的这些形象, 都是促进向前的重点. 

一直反复出现.
隐喻到故事.

与客户无关的, 就不要说.

## 英雄之旅: 主角和创作者.

主角在 bp 里完成了他的英雄之旅. 
我们也在制作 BP 的过程中,完成了我们的. 

当我认为, 就算一个人也要把项目独立完成的时候, 这个项目才有了真正完成的可能. 团队中每个人都是这么想,也是这么做的. 前面已经提到了每位队员都做了什么. 项目每个过程中, 遇到的很多小困难, 都是组员的能力和灵感化解, 遇到大家很幸运, 这是属于我们的凤头.
这个作品算是第一个我真正意义上的作品. 一样担当的起豹尾.

附表: 使用的认知写作课原理和技巧

逻辑
故事
字句
文采

编号 | 写作技巧 | 使用 | 页码
---- | ---- | ---- | ---- 
1 |
2 | 心流 | 灵感显现 | 参见 p1
3 | 组块 | 篇章信息结构: 三段论: 1-4-1, 开篇,特点,回归 |
4 | 组块 | 路演解说, 四个组块 |
5 | 空间优先 | 办公室 - 树林 - 办公室 | 
6 | 远距联想 | github 树, 树叶, 树枝, 森林 |
7 | 复制子 | 协作本来是自然的事情 
8 | 英雄之旅 | 
9 | 情感指数 | 摘脑壳的痛苦, 看到全球的风景, 解决问题的快乐
10 | 卡片 | keynote , 人物卡
11 | 大脑是个吝啬鬼 | 句子尽量简单, 主谓宾
12 | 大脑爱脑补 | 自己补完回来的样子 | 27
13 | 大脑喜欢模式 | 英雄之旅
14 | 大脑爱惊奇 | 摘脑壳
15 | 大脑爱情绪 | 悲伤到开心
16 | 结构隐喻 |
17 | 方位隐喻 | 快乐为上, 上树看风景 |
18 | 本体隐喻 | 无形的 github 变成实体的大树 
19 | 图式 | 树型
20 | 框架 | 出走-回归
21 | 象似性原则 |
22 | 经济原则
23 | 非范畴化 | 
24 | 修辞以立其诚
25 | 修辞以立其真
26 | 修辞以立其感 
27 | 辞格演绎
28 | 时空变形技法 
29 | 交流的非连续性
30 | 告白与提问 | 你要不要跟到树上去?
31 | 零度
32 | 摸索
33 | 四种时空变形
34 | 近义积累
35 | 模糊表达
36 | 转喻/侧写
37 | 对比 | 
38 | 反义互饰和悖论
39 | 讽喻
40 | 反讽
41 | 暗示 | 恶心暗示不开心
42 | 比喻
43 | 最小故事 | 光明 
44 | 心理理论
45 | 意向性 | 小明怎么想, 看小明的人怎么想
46 | 邓巴数字
47 | 树形结构 | 树
48 | 悲剧中找快乐

**Comment by Irene6161** [comment]
### 1.决心加入，到全情投入

在开始组建团队计划BP的时候，一直在纠结自己的想法，一是苦于自己没有更好的项目，二是苦于偏内向的性格不愿意主动去加入团队，但是最终打败自己纠结的是想要和优秀同侪建立更深联系的想法。
在浏览了所有的项目之后，被GithubBP的项目吸引，被团队的成员吸引，想要加入这个团队，于是找到广鹤私聊，非常感谢广鹤在这个阶段接受我的加入，让我对于认知写作有一个更好的交代。

### 2.坏的开始是成功的一半

正如上文广鹤所说，找到隐约，是故事的核心，在经过多次的沟通和脑洞之后，我们开始有了雏形。这个阶段见识了大家的才能和对于认知写作的了解，广鹤很能抓住事物的本质，绪龙擅长制造戏剧性的冲突，永菲总能冷静地在旁边把我们过于发散的思维及时拉回来。

在确定了故事之后，团队分工，拆分任务，每个人专注于自己的任务，其中最辛苦的是广鹤，因为是组长，所以承担了更多，除了故事的宏观要把控，还要沟通协调每个组员的，还有最后当我们决定用画图来表现故事的时候，永菲承担了所有的插画。在这样的写作之下，我们完成了最小雏形，虽然和大家的BP相比有很多不足，但是只有开始最小行动，才能让行动继续起来，这也是我们的信心。

### 3.回归文字的推敲才是根本

参加完了路演的预演之后，看到了我们BP的很多问题，于是罗列下来开始了新一轮的修改。我们把重心放在了文字本身，在经过多次的协调和调整之后，故事主线越来越清晰了。

### 4.一边播种一边收货

其实很明确，自己有很多的不足，从去年加入开智到现在，尤其是接触了优秀的同侪，发现了自己很多有待改善的问题，这是惊喜的，慢慢从之前的迷茫状态开始走向清晰的未来，我走得慢，但是也在一小步一小步的向前，这是开智对于我最大的收获。

**Comment by ghost** [comment]
- 从 Py103，到 Writer004，再到自怼圈，看到广鹤一路的成长和努力，被深深打动，尤其在怼圈，她使用 Github 的进阶能力大增，激发我对「远距协同创作」产生了极大的兴趣，毫不犹豫的申请加入了 GithubBP 战队。
- 广鹤在 Zoom 中与我们分享她对 Github 的理解和探索，很梦幻般大树的隐喻，不知不觉竟然从感性的一面激励了我，相信也激励了大多数的人，更有信心探索 Github 的进阶功能。
- 看似是 Github 的商业推广书，其背后隐含的是我们对黑客世界与黑客精神的追求。

> 广鹤的梦想、六一的思路、永菲的作品，集结了这个全世界最可爱的 GithubBP，深深的为三位可爱的女生骄傲。

**Comment by tyf0420** [comment]
非常喜欢广鹤的思想与文字，恰好她发起的BP我也十分感兴趣，很荣幸能参与。  
  
大家在zoom上的讨论都非常精彩。广鹤侃侃而谈她美妙而又惊奇的想法，六一善于切入要点，提出精准的改进意见，绪龙经常提出全新的角度。在此过程中，常觉自己太过笨拙，大家刚好在图画方面遇到了些障碍，我只能尽绵薄之力在这方面做一些贡献。感谢广鹤耐心提出修改建议，让我不断完善。  
  
合作创作BP的过程中，我的一窥见同伴们思考的冰山一角，他们如何敲定雏形，如何用课程的知识将其丰满和裁剪。感谢各位。
