### ISSUE TITLE
故事大概, 来修改吧.

### ISSUE THREAD

**Issue by liguanghe** [13416136446/BP_Github#5]
你在砖房子里打着电脑, 和同事沟通, 跑来跑去. 你很累, 想快点工作完去度假, 为了可以快点工作, 下班走出砖房子, 你开始在外面寻找工具, 来加快自己的工作, 你捡到很多的果实, 这些果实看起来可以帮助你, 但是要花费时间去适应它们, 因为这些果子有自己的逻辑和不同的使用场景. 你在适应他们的时候, 用了大量的时间. 这些果子之间互相也不能互通. 

在一个又一个硬掉的果子之后, 你发现, 花在效率工具上的时间, 远比用他们节省的时间还多. 这时, 幸运的是, 你顺瓜摸蔓, 见到了 果子连着的 树枝 , 顺着这个树枝, 你看到了 github 这颗大树, 你发现, 所有的果子都是从树上掉下来的, 树上住着产果子的人, 他们自由自在, 通过和树的直接连接, 达到了和其他人无障碍快速交流, 这正是你的工作里遇到阻碍的重要原因,  你看到他们快速的将自己的想法传递给别人, 不断的生成新的果子, 你很容易找到自己需要的果子, 互相引用, 又产生新的枝蔓和果子, 这棵树在不断的壮大, 越往上, 阳光越美, 视野越广阔.

你也发现, 这棵大树已经生满全球, 根系与 web 共生, 与人性共生. 活着, 便是无休止的对话, github 符合对话的所有特质. 

你开始上树, 过上了同样自由的生活, 不仅想法可以传遍全球, 你的身体也自由了, 只要有电脑, 你可以在任何地方工作.

冰山下面:

git 文件系统(生成/管理)
活着, 就是无休止的对话 (语言本能和写作课中说到的),和自己, 和别人. 

写出来, 让自己明白
写出来, 散播出去.
对话, 文字描述清楚了, 才能讲清楚. 

so , 活着, 就是不断的制造文字, 和自己, 和别人.

这些文字以文件的形式四处流动, 
这就是 github 生态系统旺盛的原因. 
编程是与机器对话及促进交流的文字
wiki 是项目协同的文字

所以说, github 是最符合人性和自然的文字生态系统

**Comment by ghost** [comment]
- 冰山下面这部分太赞了，脑中的画面油然而生。

**Comment by liguanghe** [comment]
冰山是说要告诉内容呢

**Comment by Irene6161** [comment]
我们的主人公形象是人吗？还是特殊形象？
我脑子里现在是冰川时代的松鼠嘻嘻

**Comment by liguanghe** [comment]
我的故事: 
在接触 github 之前, 每天在办公室做着重复的工作, 为了能够快点完成工作, 减少重复的沟通,我去找了很多工具, 有 印象笔记/奇妙清单/坚果云等等等等, 还专门将他们统一起来, 用他打造属于我的系统, 可是打通他们很困难, 维护起来也很辛苦,教会其他同事使用更困难.
直到我遇到 github , 发现它更符合人工作的特点, 在 issue 上,我会设定任务,按时完成,将他们变成 wiki 或者 作品, 开始以输出为导向, 创作和输出. 每一次操作都会被记录, 这让我更有责任感, 写字的时候无时无刻不考虑同事们是否容易看懂. 会为别人着想. 而当我想学习新事物的时候, 只需要在 github上搜索, 看到现有的作品都是开源的, 免费的放在那里, 任你取用. 他们的介绍也都是为你着想, 简单明了容易上手. 不仅仅是工具, 而是思维方式, 变得更开放, 更愿意为他人着想, 学习的更快, 创造也变得容易. 不必担心储存的问题, 也不必担心版本控制. 这些 github 都替我想好了. 
而且在这里, 我的思维可以连接到全球的聪明人, 很快找到与我有相同想法的人, 比如, 我想爬取法律词汇, 有人已经做了, 这个人跟我是同好. 
不仅思维自由, 身体也自由了, 因为可以在网上随时工作, 那么, 想在哪里工作都可以.

对我来说, github 是一个根植于全球 web 和人性的大榕树, 树上的居民们, 与自然和人们无障碍的极速交流, 不断产生新的想法, 实践并转化为果子, 这些果子有些落在地上, 供人使用, 也有些供人调用, 随时生成新的果子和枝蔓, 人们顺着向上, 视野越来越开阔, 阳光也越来越充足. 成为树上的居民, 就不再有以前的烦恼.

**Comment by Irene6161** [comment]
关于隐喻的故事模型

## 果子女孩

女孩靠吃果子维持生命，所以果子的好坏就代表着她得身体健康和生命状态。

女孩平时都是在山间和林地捡果子吃，一边捡一边收集，果子很多，足以裹腹。

但，虽然可以维持生存，这些果子或是有些吃了坏肚子，或是成了干掉的果干，或熟过了头。

女孩想找到好果子。

于是她发现，最新掉下来的果子都是好果子，于是她想，如果我在果子掉下来之前就得到它们呢？

女孩开始摘果子，她吃到了前所未有的美味，果子不仅漂亮，饱满，咬一口，汁水随着脆响浸满了舌头，味蕾的所有细胞都跳起了舞，连内心都腾升一股愉悦之感。她觉得幸福极了。
她看着果子微笑，开始爬树摘果子。

即使树上的果子，也有不好吃——那些生涩的，树叶一样颜色的，女孩默默记在心里，一边摘果子，一边往大树更高处爬。

女孩发现，越是长在高处的果子，每天喝阳光风雨打招呼的果子，越是美味。

女孩坐在高高地树枝上，不仅吃到了鲜美的果子，还看了美丽的风景，她看到了——更多的高大的果树。她向往更广阔的天地，她想尝尝更多的果子，于是她开始去爬更多的大树。

她发现了，长果子的大树遍布了整个地球，只要你主动爬上去，动手摘了试试，就总能发现好吃的果子。每尝过一棵树的果子，她都会给大树浇水，把果核埋在树下。

女孩一边寻觅，一边攀爬，并且把好吃的果子给更多的人喝动物分享，让更多的人一起爬树，摘果子，给大树浇水，埋下更多的果核，长出更多的大树。

————————————————————————————————————-
每一段可以作为keynote的一张，讲述这画面和故事，最后结尾的时候，提炼出slogan，作为结尾。

**Comment by liguanghe** [comment]
@Irene6161 baby, 要把观众们代入进来, 怎么代入到他们吃果子的情景呢~

**Comment by tyf0420** [comment]
@Irene6161   
- 在女孩给大树浇水、把果核埋在树下之前，加上看到有其他人先这样做从而被带动会不会更好...？  
- 如果把github比作果树，'她看到了——更多的高大的果树。她向往更广阔的天地，她想尝尝更多的果子，于是她开始去爬更多的大树。'中更多的果树会不会不合适，改成果树延展的躯体...就整体还是一个。  
  
提的都是一些很小的点，可能帮助不是很大，不好意思><

**Comment by Irene6161** [comment]
@tyfff 
补充一个情节：

女孩在继续找更多的果子的途中，看到了吃坏肚子的小熊，或者饿的不得了的小孩，然后把好吃的果子分给他们，并且带着他们一起爬树，吃果子，给大树浇水。

@13416136446   对于观众来说，就是看到这个故事。

源域                         目标域
git hub        ——     大树
地上的果子 ——     其他工具
好吃的果子 ——     github及其工具
爬树            ——     主动探索
浇水            ——     开源
分享果子     ——    让更多的人使用，共建美好

求大家的意见和批评哈，也不一定要用这个故事，就是我脑子里就出现了这个故事，有很多画面，所以就先写下来。

**Comment by liguanghe** [comment]
挺好的故事, 突出了真, 恩, github 有很理智的部分, 看怎么体现出来~ 今天忘了这部分

**Comment by tyf0420** [comment]
突然想到，如果需要逆转，那么  
- 最初女孩认为她找到的果子很美味  
- 后来找到果树，果子的源头，发现有更多新鲜的果子   
- 醒悟原先的果子其实是苦涩、干瘪的  
  
再后面就接分享那部分的内容。  
以上是我一点点不成熟的小建议嘿嘿。  
具体怎么丰满、夸张就还看各位大神了。

**Comment by liguanghe** [comment]
本宝宝不喜欢果子, 重点是树, 不是果子
呜呜呜呜

**Comment by liguanghe** [comment]
树啊, 在树上生活的人们呐, 跟树的交流和跟人的交流啊

**Comment by larry8916** [comment]
看到广鹤上面的“我的故事”段，很有启发！

总结一下Github的优点，以及我认为我们应该着重强调的内容：

###  Github优点：
1. > 每一次操作都会被记录.

这会产生一种郑重的仪式感，让自己每一步的动作都有意义，也更认真。

2. > 注重协作
写字的时候无时无刻不考虑同事们是否容易看懂. 会为别人着想.

3.  智力黑洞

汇聚了二十一世纪最为性感的头脑，如XX，XX，深处牛人圈，学习全世界最聪明的头脑，进行项目思考管理，以及团队合作的高效。

**Comment by liguanghe** [comment]
交付 -> [5.3 故事初稿, 来改吧 · Issue #7 · 13416136446/BP_Github](https://github.com/13416136446/BP_Github/issues/7)
