### ISSUE TITLE
keynote 

### ISSUE THREAD

**Issue by liguanghe** [13416136446/BP_Github#8]
- 链接: https://www.icloud.com/keynote/0tE3Ra4FDZoYq3rvaYzaLPDMQ
- 改动:  第三部分和第四部分有点变动, 把全球的大树移到了第三部分结尾, 第四部分是, 他们的树枝,开始变成大树, 跟别的连接.
- 字体: 雅痞 简

**Comment by liguanghe** [comment]
改动可能影响主干剧情的, 在这里写一下
@Zxlon @tyfff

**Comment by Irene6161** [comment]
第一部分的故事已经更新，求大家的意见。

**Comment by Irene6161** [comment]
总结一下目前广鹤给的建议：
图：
- 第一页要有办公室的门，空间优先
- 增加同事的形象
- 所有的同事脑子都要在墙上
- 需要找永菲协助

文字
- 需要增加美感（翻一翻古诗,看看有没有跟协作和开颅有关的句子, 稍加改动和拼接）

**Comment by liguanghe** [comment]
第四部分灵感: 龙猫, 55分30秒开始到58分
http://www.aixifan.com/v/ac1737476

**Comment by Irene6161** [comment]
在永菲宝宝的帮助下，更新了一版，求拍。

**Comment by liguanghe** [comment]
@Irene6161 
p1. 文字变成" 早晨, 办公室".
    p5 的办公室卡片放到 p1 左边
    这张的表情还是开心的啦,之后几 p 慢慢不开心
p2. 小明的脑壳和老板的脑壳都应该摘下来啦

图片整体很好咯, 接下来是文字, 看看是不是一些描写性的语句, 而不是总结性的陈述句. 不是谁做了什么, 而是当时的场景, 暗示别人知道谁做了什么.

乱麻的描写什么的.

**Comment by ghost** [comment]
## 好赞

- 画面好漂亮，这很有可能成为史上最可爱的 Github BP 。

- 从星期日开始是否更好一些？
  - 毕竟我们都是从 ch0 起跑的。
  - 星期天是不用摘下脑壳的玩耍。
  - 放下脑壳意味着放下自己吧，传统的工作中因缺少协同，都是重复造轮子，有很多无用功。
  - 这一可以和最后面连接上，放一个小包袱在这里，以后用大树了，就不用摘下脑壳了，不用时间管理而是心流管理，即使陪孩子在森林玩耍，也能抽上 15min 回复 issue 。

- 老板说出的话是浆糊，可以直接指出一些，比如：
  - 打电话通知开会
  - 微信群信息丢失
  - 把那本书打印出来
  - 大家添加...

- 同事给的是浆糊，画一个直观的表格如何？
  - 例子：World 做的表格，中文字、数字都在同个格子里，难解难分。

- 忍着脑袋被塞的恶心，把信息揉成一张图跑起来
  - 在老板发怒之前，加上一张，很多人都是这样子的，不仅仅小明一个人。
  - 想想画面怎么表现，很忙很忙，却总是重复造轮子，干傻乎乎的事情。

- 猫头鹰的隐喻究竟应该是谁呢？
  - 单纯的一只动物？
  - 脑壳上有 OpenMind 的一个默默下班后来跟小明分享 GIthub 的同事或朋友？
  - 如果是后者，那么我们接下来的森林就好画一点了。
  - 例子：大树和森林里面的生物就好安排了，阳老、大妈、所有人都可以画上去啦，哈。

> 抱歉小伙伴们，我没啥贡献，只顾叨叨了一顿，目前的作品已经超出想象了。

**Comment by liguanghe** [comment]
@Zxlon 交出你的 part~~

**Comment by liguanghe** [comment]
官方 生动的例子(大家都要看): https://www.youtube.com/watch?v=w3jLJU7DT5E
![](http://ww3.sinaimg.cn/large/006tNbRwgy1ffct5ecybij30zs0jowqr.jpg)
@tyfff 永菲, 这张是在到全球之前的感觉, 上面视频第29秒开始

**Comment by liguanghe** [comment]
@Irene6161  上面的视频, 可以看一下

**Comment by liguanghe** [comment]
第二部分灵感及图片素材: https://gonzalo-bulnes.github.io/blog/gardening_with_git/context-from-scratch.html
![](http://ww3.sinaimg.cn/large/006tNbRwgy1ffczhms6ldj30oi0ww0v6.jpg)
![](http://ww4.sinaimg.cn/large/006tNbRwgy1ffczhm8qynj30m00vuwgt.jpg)
![](http://ww1.sinaimg.cn/large/006tNbRwgy1ffczhmc302j30n20wwacu.jpg)
第二部分大纲:
![](http://ww3.sinaimg.cn/large/006tNbRwgy1ffd0349zhej31kw16ob29.jpg)

**Comment by ghost** [comment]
@广鹤
我的第三部分吗？要跟着你们前面的思路走哈

**Comment by liguanghe** [comment]
第二部分贯穿全 key 的图: ![](http://ww4.sinaimg.cn/large/006tNbRwgy1ffd29c8ktlj30sg0g0wjv.jpg)

**Comment by liguanghe** [comment]
@Zxlon 
风格方面, 人物是第一部分 六一画出的风格
第二/三部分, 猫头鹰改成 章鱼猫 的卡通图像. 大树的形象是上面几张图片.
一直出现的树枝, 用直的树枝(上上上图)
第三部分, 是去到其他树上, 复制树枝回来, 跟自己的项目连接, 变出更多的图片.

**Comment by Irene6161** [comment]
我们是不是先把各自负责部分的文字先描写完整，然后把整个故事拼接起来？

**Comment by liguanghe** [comment]
![](http://ww4.sinaimg.cn/large/006tNc79gy1ffivb8vqeqj31a80w2dkz.jpg)

**Comment by liguanghe** [comment]
![](http://ww1.sinaimg.cn/large/006tNc79gy1ffivl4wqwyj318o0ykgrl.jpg)

**Comment by Irene6161** [comment]
我又调整了一些顺序：
1.把小明回来了（英雄归来）的篇章提前了；
2.最后的结尾是全球 共生；
3.微调了一些文字。

**Comment by liguanghe** [comment]
@Irene6161 还是改回来咯, 他的回来. ( bp已改)
主体部分为了展示小明原本不会的东西. 包括全球共生. 
这些都在第二部分.最后一页小明回来就好咯

**Comment by Irene6161** [comment]
我把最新的意见放在keynote上，红字部分，广鹤你看完可以直接删掉。
还有几个问题：

1.如果基本确认，我们就要开始排版和动画制作然后转成视频了。
2.配乐有没有最终确定？我的建议之前都放在了issue里。
3.文字是不是可以最终定稿了？我的蓝色的字都是建议，如果觉得不合适，广鹤可以直接删掉，我没有异议。
4.最后一个画面，不是很明白，个人觉得“共生”作为结尾更合适。因为我们的BP其实是靠文字讲述的，没有声音在旁边讲解，所以看文字不明白的话，观众可能也不明白。

**Comment by Irene6161** [comment]
我们是确定了明晚的路演是吗？
今晚是否需要彩排一下？
