### ISSUE TITLE
图片素材

### ISSUE THREAD

**Issue by liguanghe** [13416136446/BP_Github#9]
有图片放在这里~我们的风格目前是这样的:
![](http://ww4.sinaimg.cn/large/006tNc79gy1ff9nalyli0j30h80db0t4.jpg)
![](http://ww1.sinaimg.cn/large/006tNc79gy1ff9naig22cj30mr0csjrd.jpg)

**Comment by ghost** [comment]
这位的图好用 --> https://zccz14.com/2017/04/05/GitHub%20Issue/

**Comment by ghost** [comment]
- if...xxx   then...Github

![](http://media02.hongkiat.com/ifttt-recipes-for-github/ifttt-github-recipe-todoist1.jpg)

**Comment by tyf0420** [comment]
形象原型是欢乐氰化物(Cyanide&Happiness)  
可以参考里面的表情  
![](http://i1.piimg.com/567571/1e4dea93f60d771b.jpg)
![](http://i4.buimg.com/567571/d24ba26f1a984df4.jpg)
![](http://i2.muimg.com/567571/f847534cbbb946c3.jpg)
![](http://i4.buimg.com/567571/11a28461e5a909d5.jpg)
![](http://i4.buimg.com/567571/43752d2b8825414e.jpg)

**Comment by tyf0420** [comment]
之前画的猫头鹰...没有issue最开始那个在网上找的简单可爱  
![](http://i1.piimg.com/567571/8f74c5d0a2bfccf2.png)
![](http://i4.buimg.com/567571/21b0143a839c32cc.png)

**Comment by liguanghe** [comment]
![](http://ww1.sinaimg.cn/large/006tNbRwgy1ffcrk01mq8j31040tl0y6.jpg)
